- name: Create Student DBs
  hosts: infra-vms-rhel9-fast-tapir
  become: true
  vars:
    students:
      - charmander
      - squirtle
      - bulbasaur
      - pikachu
    db_state: present

  tasks:
  - name: Create student databases
    community.postgresql.postgresql_db:
      name: "{{ item }}"
      state: "{{ db_state }}"
      login_host: localhost
      login_user: postgres
      login_password: "oPgJTTu0hP57NBx2"
    with_items: "{{ students }}"
