- name: Create Student DBs
  hosts: infra-vms-rhel9-fast-tapir
  become: true
  vars:
    students:
      - charmander
      - squirtle
      - bulbasaur
      - pikachu

  tasks:
  - name: Collect all info
    community.postgresql.postgresql_info:
      login_user: "{{ login_user }}"
      login_password: "{{ login_password }}"
      filter: "roles"
    register: postgres_info
    when: db_state == "absent"

  - name: Omit postgres user
    set_fact:
      postgres_info: "{{ postgres_info | 'postgres' }}"
    when: db_state == "absent"

  - name: Diff users
    set_fact:
      students: "{{ postgres_info | students }}"
    when: db_state == "absent"

    - name: Display Diff
      debug:
        var: students

  - name: Manage student databases
    community.postgresql.postgresql_db:
      login_user: "{{ login_user }}"
      login_password: "{{ login_password }}"
      name: "db-{{ item }}"
      state: "{{ db_state }}"
    with_items: "{{ students }}"

  - name: Manage student users
    community.postgresql.postgresql_user:
      login_user: "{{ login_user }}"
      login_password: "{{ login_password }}"
      name: "{{ item }}"
      password: "Password123!!"
      state: "{{ db_state }}"
    with_items: "{{ students }}"

  - name: Manage student privs
    community.postgresql.postgresql_privs:
      login_user: "{{ login_user }}"
      login_password: "{{ login_password }}"
      db: "db-{{ item }}"
      privs: ALL
      role: "{{ item }}"
      obj: ALL_IN_SCHEMA
    when: db_state == "present"
    with_items: "{{ students }}"
