- name: Create Student DBs
  hosts: infra-vms-rhel9-fast-tapir
  become: true
  vars:
    students: "{{ ad_group_members }}"

  tasks:
  - name: Collect all info
    community.postgresql.postgresql_info:
      login_user: "{{ login_user }}"
      login_password: "{{ login_password }}"
      filter: "roles"
    register: postgres_info

  - name: Manage student databases
    community.postgresql.postgresql_db:
      login_user: "{{ login_user }}"
      login_password: "{{ login_password }}"
      name: "db-{{ item }}"
      state: "{{ db_state }}"
    with_items: "{{ students }}"

  - name: Manage student users
    community.postgresql.postgresql_user:
      login_user: "{{ login_user }}"
      login_password: "{{ login_password }}"
      name: "{{ item }}"
      password: "Password123!!"
      state: "{{ db_state }}"
    with_items: "{{ students }}"

  - name: Manage student privs
    community.postgresql.postgresql_privs:
      login_user: "{{ login_user }}"
      login_password: "{{ login_password }}"
      db: "db-{{ item }}"
      privs: ALL
      role: "{{ item }}"
      obj: ALL_IN_SCHEMA
    when: db_state == "present"
    with_items: "{{ students }}"
