- name: Create Student DBs
  hosts: infra-vms-rhel9-fast-tapir
  become: true
  vars:
    students:
      - charmander
      - squirtle
      - bulbasaur
      - pikachu
    db_state: present

  tasks:
  - name: Permit traffic for postgres
    ansible.posix.firewalld:
      port: 5432/tcp
      permanent: true
      state: enabled
  
  - name: Create student databases
    community.postgresql.postgresql_db:
      login_user: "{{ login_user }}"
      login_password: "{{ login_password }}"
      name: "db-{{ item }}"
      state: "{{ db_state }}"
    with_items: "{{ students }}"

  - name: Create student users
    community.postgresql.postgresql_user:
      login_user: "{{ login_user }}"
      login_password: "{{ login_password }}"
      db: "db-{{ item }}"
      name: "{{ item }}"
      password: "Password123!!"
    with_items: "{{ students }}"

  - name: Grant student privs
    community.postgresql.postgresql_privs:
      login_user: "{{ login_user }}"
      login_password: "{{ login_password }}"
      db: "db-{{ item }}"
      privs: ALL
      role: "{{ item }}"
      obj: ALL_IN_SCHEMA
    with_items: "{{ students }}"
