- name: Sync Student DBs
  hosts: postgresql
  become: true
  gather_facts: false
  vars:
    students: "{{ ad_group_members }}"
    roles_to_ignore:
      - "postgres"

  tasks:
  - name: Add needed student databases
    community.postgresql.postgresql_db:
      login_user: "{{ login_user }}"
      login_password: "{{ login_password }}"
      name: "db-{{ item }}"
      state: "present"
    with_items: "{{ students }}"

  - name: Add needed student users
    community.postgresql.postgresql_user:
      login_user: "{{ login_user }}"
      login_password: "{{ login_password }}"
      name: "{{ item }}"
      password: "{{ lookup('community.general.random_string', min_lower=1, min_upper=1, min_special=1, min_numeric=1) }}"
      state: "present"
    with_items: "{{ students }}"

  - name: Manage student privs
    community.postgresql.postgresql_privs:
      login_user: "{{ login_user }}"
      login_password: "{{ login_password }}"
      db: "db-{{ item }}"
      privs: ALL
      role: "{{ item }}"
      obj: ALL_IN_SCHEMA
    with_items: "{{ students }}"

  - name: Collect all info
    community.postgresql.postgresql_info:
      login_user: "{{ login_user }}"
      login_password: "{{ login_password }}"
      filter: "roles"
    register: postgres_info

  - name: Filter roles
    ansible.builtin.set_fact:
      roles_after_filter: "{{ postgres_info.roles | difference(roles_to_ignore) }}"

  - name: Determine diff
    ansible.builtin.set_fact:
      roles_to_remove: "{{ roles_after_filter | difference(students) }}"

  - name: Remove unneeded databases
    community.postgresql.postgresql_db:
      login_user: "{{ login_user }}"
      login_password: "{{ login_password }}"
      name: "db-{{ item }}"
      state: "absent"
    with_items: "{{ roles_to_remove }}"

  - name: Remove unneeded student users
    community.postgresql.postgresql_user:
      login_user: "{{ login_user }}"
      login_password: "{{ login_password }}"
      name: "{{ item }}"
      state: "absent"
    with_items: "{{ roles_to_remove }}"
