- name: Create Student DBs
  hosts: infra-vms-rhel9-fast-tapir
  vars:
    students:
      - charmander
      - squirtle
      - bulbasaur
      - pikachu
    db_state: present
  tasks:
  - name: Create student databases
    community.postgresql.postgresql_db:
      name: "{{ item }}"
      state: "{{ db_state }}"
      login_host: postgresql-demo
      login_user: "user7UE"
      login_password: "oPgJTTu0hP57NBx2"
    with_items: "{{ students }}"
