- name: Create Student DBs
  hosts: infra-vms-rhel9-fast-tapir
  become: true
  vars:
    students:
      - charmander
      - squirtle
      - bulbasaur
      - pikachu
    db_state: present

  tasks:
  - name: Create student databases
    community.postgresql.postgresql_db:
      name: "{{ item }}"
      state: "{{ db_state }}"
      login_host: localhost
      login_user: postgresql
      login_password: "oPgJTTu0hP57NBx2"
    with_items: "{{ students }}"
    become_method: su
    become_user: postgres


  "msg": "Failed to set permissions on the temporary files Ansible needs to create when becoming an unprivileged user (rc: 1, err: chmod: invalid mode: ‘A+user:postgresql:rx:allow’\nTry 'chmod --help' for more information.\n}). For information on working around this, see https://docs.ansible.com/ansible-core/2.15/playbook_guide/playbooks_privilege_escalation.html#risks-of-becoming-an-unprivileged-user#risks-of-becoming-an-unprivileged-user",
