- name: Get AD group members
  hosts: activedirectory
  gather_facts: false

  tasks:
  - name: Query group
    ansible.windows.win_powershell:
      script: "(Get-ADGroupMember -Identity '{{ ad_group_name }}').samaccountname"
    register: ad_group_members

  - name: Set output as stat
    ansible.builtin.set_stats:
      data:
        students: "{{ ad_group_members.output }}"
